-- Identity: users and their roles. Portable DDL only (H2 PostgreSQL-mode + real Postgres) —
-- see the flyway-migrations skill.

CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255)  NOT NULL,
    password_hash VARCHAR(100)  NOT NULL,
    full_name     VARCHAR(200)  NOT NULL,
    phone         VARCHAR(20),
    enabled       BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(128)  NOT NULL,
    updated_by    VARCHAR(128)  NOT NULL,
    CONSTRAINT uq_app_user_email UNIQUE (email)
);

-- Backs Set<Role> on User (@ElementCollection) — a fixed two-role model (AGENTS.md: advanced
-- auth/roles beyond admin+customer is out of scope), so no separate role entity/table.
CREATE TABLE user_role (
    user_id BIGINT      NOT NULL REFERENCES app_user(id),
    role    VARCHAR(20) NOT NULL CHECK (role IN ('ADMIN', 'CUSTOMER')),
    CONSTRAINT pk_user_role PRIMARY KEY (user_id, role)
);
