-- Reference data: cities -> theaters -> screens -> seats, plus movies. Portable DDL only.

CREATE TABLE city (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    state      VARCHAR(100),
    country    VARCHAR(100) NOT NULL,
    timezone   VARCHAR(50)  NOT NULL,
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by VARCHAR(128) NOT NULL,
    updated_by VARCHAR(128) NOT NULL,
    CONSTRAINT uq_city_name_state UNIQUE (name, state)
);

CREATE TABLE theater (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id    BIGINT       NOT NULL REFERENCES city(id),
    name       VARCHAR(200) NOT NULL,
    address    VARCHAR(500) NOT NULL,
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by VARCHAR(128) NOT NULL,
    updated_by VARCHAR(128) NOT NULL,
    CONSTRAINT uq_theater_city_name UNIQUE (city_id, name)
);
CREATE INDEX idx_theater_city ON theater (city_id);

CREATE TABLE screen (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    theater_id  BIGINT      NOT NULL REFERENCES theater(id),
    name        VARCHAR(50) NOT NULL,
    total_seats INT         NOT NULL DEFAULT 0,
    active      BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by  VARCHAR(128) NOT NULL,
    updated_by  VARCHAR(128) NOT NULL,
    CONSTRAINT uq_screen_theater_name UNIQUE (theater_id, name)
);
CREATE INDEX idx_screen_theater ON screen (theater_id);

CREATE TABLE seat (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    screen_id     BIGINT      NOT NULL REFERENCES screen(id),
    row_label     VARCHAR(5)  NOT NULL,
    seat_number   INT         NOT NULL,
    display_label VARCHAR(10) NOT NULL,
    category      VARCHAR(20) NOT NULL CHECK (category IN ('REGULAR', 'PREMIUM', 'RECLINER')),
    active        BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(128) NOT NULL,
    updated_by    VARCHAR(128) NOT NULL,
    CONSTRAINT uq_seat_screen_row_number UNIQUE (screen_id, row_label, seat_number)
);
CREATE INDEX idx_seat_screen ON seat (screen_id);

CREATE TABLE movie (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR(300) NOT NULL,
    language         VARCHAR(50)  NOT NULL,
    duration_minutes INT          NOT NULL,
    certification    VARCHAR(20),
    synopsis         VARCHAR(2000),
    release_date     DATE,
    active           BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by       VARCHAR(128) NOT NULL,
    updated_by       VARCHAR(128) NOT NULL
);
CREATE INDEX idx_movie_title ON movie (title);
CREATE INDEX idx_movie_active_release ON movie (active, release_date);
