-- Shows, per-show pricing, seat holds, and the materialized per-show-per-seat occupancy row.
-- This migration is the schema half of the concurrency design documented in AGENTS.md §4.

CREATE TABLE show_event (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    screen_id      BIGINT       NOT NULL REFERENCES screen(id),
    movie_id       BIGINT       NOT NULL REFERENCES movie(id),
    -- Denormalised from screen -> theater -> city. Derived in ShowService from the screen's own
    -- theater/city, never accepted from the request DTO — see AGENTS.md domain note G-6.
    city_id        BIGINT       NOT NULL REFERENCES city(id),
    starts_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    ends_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    status         VARCHAR(20)  NOT NULL CHECK (status IN ('SCHEDULED', 'CANCELLED', 'COMPLETED')),
    sales_open_at  TIMESTAMP WITH TIME ZONE,
    sales_close_at TIMESTAMP WITH TIME ZONE,
    currency       VARCHAR(3)   NOT NULL DEFAULT 'INR',
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by     VARCHAR(128) NOT NULL,
    updated_by     VARCHAR(128) NOT NULL
);
-- Hot browse query: "shows in city X for movie Y on date D" (Show.java's denormalisation).
CREATE INDEX idx_show_city_starts ON show_event (city_id, starts_at);
CREATE INDEX idx_show_movie_starts ON show_event (movie_id, starts_at);
-- Backs the screen-overlap check: lock the screen row, then scan its shows for a time overlap.
CREATE INDEX idx_show_screen_starts ON show_event (screen_id, starts_at);

-- Per-show, per-category base price. Looked up at browse/quote time, snapshotted onto
-- booking_charge at booking time — never stored on show_seat (would duplicate N times per show
-- and make a price change an UPDATE over hundreds of rows).
CREATE TABLE show_price (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    show_id        BIGINT       NOT NULL REFERENCES show_event(id),
    seat_category  VARCHAR(20)  NOT NULL CHECK (seat_category IN ('REGULAR', 'PREMIUM', 'RECLINER')),
    base_amount    NUMERIC(12,2) NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by     VARCHAR(128) NOT NULL,
    updated_by     VARCHAR(128) NOT NULL,
    CONSTRAINT uq_show_price_category UNIQUE (show_id, seat_category)
);

-- The hold aggregate. A header row per hold-attempt, referenced by the show_seat rows it covers
-- (show_seat.hold_id). Makes the per-user active-hold cap a one-row count, hold extension a
-- one-row UPDATE, and gives the API a stable reference to return to the client.
CREATE TABLE seat_hold (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    show_id       BIGINT       NOT NULL REFERENCES show_event(id),
    user_id       BIGINT       NOT NULL REFERENCES app_user(id),
    status        VARCHAR(16)  NOT NULL CHECK (status IN ('ACTIVE', 'CONSUMED', 'EXPIRED', 'RELEASED')),
    seat_count    INT          NOT NULL,
    expires_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(128) NOT NULL,
    updated_by    VARCHAR(128) NOT NULL
);
-- Enforces app.hold.max-active-holds-per-user on the hot contended path (checked on every hold
-- attempt) without a cross-show scan.
CREATE INDEX idx_seat_hold_user_status ON seat_hold (user_id, status);
CREATE INDEX idx_seat_hold_status_expiry ON seat_hold (status, expires_at);

-- The authoritative occupancy row: one per (show, seat), created when the show is provisioned.
-- show_seat.status is the truth about what is occupied; booking_seat (added later) is the record
-- of what was sold. See AGENTS.md §4 for why per-show-seat materialization, single-table locking
-- by primary key, and the @Version backstop are all deliberate.
CREATE TABLE show_seat (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    show_id          BIGINT      NOT NULL REFERENCES show_event(id),
    seat_id          BIGINT      NOT NULL REFERENCES seat(id),
    status           VARCHAR(16) NOT NULL CHECK (status IN ('AVAILABLE', 'HELD', 'BOOKED', 'BLOCKED')),
    hold_id          BIGINT      REFERENCES seat_hold(id),
    -- Denormalised from seat_hold.expires_at, written in the same transaction as hold_id, always.
    -- Bought: the lazy-expiry check and the seat-map read are both single-table and index-covered
    -- with no join to seat_hold. Two places to keep in sync; both written together, always.
    hold_expires_at  TIMESTAMP WITH TIME ZONE,
    booking_id       BIGINT, -- FK added in the booking migration once booking exists
    version          BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT uq_show_seat UNIQUE (show_id, seat_id)
);
-- The single hottest read in the system: the seat map for a show.
CREATE INDEX idx_show_seat_show_status ON show_seat (show_id, status);
-- The hold-expiry sweeper's scan: WHERE status='HELD' AND hold_expires_at <= ?
CREATE INDEX idx_show_seat_hold_expiry ON show_seat (status, hold_expires_at);
CREATE INDEX idx_show_seat_hold ON show_seat (hold_id);
