-- Discount codes. Seat-category/weekend pricing is already handled by show_price (per-show,
-- per-category base amount, set at show creation) -- a separate pricing-rule engine would be
-- equivalent expressive power for far more code, so it's deliberately not built. See AGENTS.md.

CREATE TABLE discount_code (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code               VARCHAR(40)   NOT NULL,
    discount_type      VARCHAR(20)   NOT NULL CHECK (discount_type IN ('PERCENTAGE', 'FLAT')),
    discount_value     NUMERIC(12,2) NOT NULL,
    min_order_amount   NUMERIC(12,2) NOT NULL DEFAULT 0,
    max_discount_amount NUMERIC(12,2),
    max_redemptions    INT           NOT NULL,
    used_count         INT           NOT NULL DEFAULT 0,
    valid_from         TIMESTAMP WITH TIME ZONE NOT NULL,
    valid_until        TIMESTAMP WITH TIME ZONE NOT NULL,
    active             BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by         VARCHAR(128)  NOT NULL,
    updated_by         VARCHAR(128)  NOT NULL,
    CONSTRAINT uq_discount_code UNIQUE (code)
);
