-- The booking aggregate. booking_charge is the itemized, signed breakdown persisted at booking
-- time (never recomputed from today's prices later); each line optionally references the seat it
-- belongs to (NULL show_seat_id = order-level, e.g. a discount or fee), which is what makes
-- pro-rata partial-seat refunds a sum over that seat's own refundable lines, not a recomputation.

CREATE TABLE booking (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_reference VARCHAR(20)   NOT NULL,
    user_id           BIGINT        NOT NULL REFERENCES app_user(id),
    show_id           BIGINT        NOT NULL REFERENCES show_event(id),
    hold_id           BIGINT        NOT NULL REFERENCES seat_hold(id),
    status            VARCHAR(24)   NOT NULL CHECK (status IN
        ('PENDING_PAYMENT', 'CONFIRMED', 'PARTIALLY_CANCELLED', 'CANCELLED', 'PAYMENT_FAILED', 'SEAT_LOST_AFTER_PAYMENT')),
    seat_count        INT           NOT NULL,
    total_amount      NUMERIC(12,2) NOT NULL,
    currency          VARCHAR(3)    NOT NULL DEFAULT 'INR',
    discount_code_id  BIGINT REFERENCES discount_code(id),
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by        VARCHAR(128)  NOT NULL,
    updated_by        VARCHAR(128)  NOT NULL,
    CONSTRAINT uq_booking_reference UNIQUE (booking_reference)
);
CREATE INDEX idx_booking_user ON booking (user_id, created_at);
CREATE INDEX idx_booking_show ON booking (show_id);

CREATE TABLE booking_seat (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id    BIGINT       NOT NULL REFERENCES booking(id),
    show_seat_id  BIGINT       NOT NULL REFERENCES show_seat(id),
    seat_label    VARCHAR(10)  NOT NULL,
    seat_category VARCHAR(20)  NOT NULL,
    status        VARCHAR(16)  NOT NULL CHECK (status IN ('ACTIVE', 'CANCELLED')),
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(128) NOT NULL,
    updated_by    VARCHAR(128) NOT NULL,
    -- NOT unique(show_seat_id alone) -- book, cancel, rebook legitimately produces two rows.
    CONSTRAINT uq_booking_seat UNIQUE (booking_id, show_seat_id)
);
CREATE INDEX idx_booking_seat_booking ON booking_seat (booking_id);

CREATE TABLE booking_charge (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id     BIGINT        NOT NULL REFERENCES booking(id),
    booking_seat_id BIGINT REFERENCES booking_seat(id),
    charge_type    VARCHAR(20)   NOT NULL CHECK (charge_type IN ('BASE', 'DISCOUNT', 'FEE', 'TAX')),
    description    VARCHAR(200)  NOT NULL,
    amount         NUMERIC(12,2) NOT NULL,
    refundable     BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by     VARCHAR(128)  NOT NULL,
    updated_by     VARCHAR(128)  NOT NULL
);
CREATE INDEX idx_booking_charge_booking ON booking_charge (booking_id);
CREATE INDEX idx_booking_charge_seat ON booking_charge (booking_seat_id);

CREATE TABLE booking_status_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id  BIGINT       NOT NULL REFERENCES booking(id),
    from_status VARCHAR(24),
    to_status   VARCHAR(24)  NOT NULL,
    reason      VARCHAR(500),
    changed_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    changed_by  VARCHAR(128) NOT NULL
);
CREATE INDEX idx_booking_status_history_booking ON booking_status_history (booking_id, changed_at);

-- show_seat.booking_id was left unconstrained in V3 pending this table's existence.
ALTER TABLE show_seat ADD CONSTRAINT fk_show_seat_booking FOREIGN KEY (booking_id) REFERENCES booking(id);
