CREATE TABLE payment (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id       BIGINT        NOT NULL REFERENCES booking(id),
    amount           NUMERIC(12,2) NOT NULL,
    currency         VARCHAR(3)    NOT NULL DEFAULT 'INR',
    status           VARCHAR(20)   NOT NULL CHECK (status IN ('SUCCEEDED', 'FAILED', 'REVERSED')),
    gateway_reference VARCHAR(100) NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by       VARCHAR(128)  NOT NULL,
    updated_by       VARCHAR(128)  NOT NULL,
    -- Double-charge is structurally impossible, not merely defended against: a booking can only
    -- ever have one SUCCEEDED-turned-authoritative payment row. Failed attempts still need their
    -- own rows for audit, so this is enforced in the service (conditional insert), not the DDL.
    CONSTRAINT uq_payment_booking UNIQUE (booking_id, gateway_reference)
);
CREATE INDEX idx_payment_booking ON payment (booking_id);

-- Tiered, most-specific-scope-wins refund policy. A booking snapshots the resolved policy id at
-- confirmation time (booking.refund_policy_id) -- editing a policy later never retroactively
-- changes what an existing customer was promised; "editing" a rule set means deactivating the
-- old rows and inserting new ones.
CREATE TABLE refund_policy (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type             VARCHAR(20)  NOT NULL CHECK (scope_type IN ('GLOBAL', 'CITY', 'THEATER', 'SHOW')),
    scope_id               BIGINT,
    min_minutes_before_show INT         NOT NULL,
    refund_percentage      NUMERIC(5,2) NOT NULL,
    active                 BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by             VARCHAR(128) NOT NULL,
    updated_by             VARCHAR(128) NOT NULL
);
CREATE INDEX idx_refund_policy_scope ON refund_policy (scope_type, scope_id, active);

CREATE TABLE refund (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id    BIGINT        NOT NULL REFERENCES booking(id),
    payment_id    BIGINT        NOT NULL REFERENCES payment(id),
    amount        NUMERIC(12,2) NOT NULL,
    reason        VARCHAR(500),
    status        VARCHAR(20)   NOT NULL CHECK (status IN ('COMPLETED', 'FAILED')),
    gateway_reference VARCHAR(100) NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(128)  NOT NULL,
    updated_by    VARCHAR(128)  NOT NULL
);
CREATE INDEX idx_refund_booking ON refund (booking_id);
