-- Transactional outbox. Written inside the same transaction as the business event (via
-- @TransactionalEventListener(BEFORE_COMMIT)), drained by a separate @Scheduled dispatcher --
-- never published directly on a plain @Async thread, which can send a confirmation for a booking
-- whose transaction then rolls back. payload is TEXT, not JSONB -- portable DDL only.
CREATE TABLE outbox_event (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dedupe_key     VARCHAR(200)  NOT NULL,
    event_type     VARCHAR(60)   NOT NULL,
    payload        VARCHAR(4000) NOT NULL,
    status         VARCHAR(20)   NOT NULL CHECK (status IN ('PENDING', 'SENT', 'DEAD_LETTER')),
    attempts       INT           NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_error     VARCHAR(1000),
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by     VARCHAR(128)  NOT NULL,
    updated_by     VARCHAR(128)  NOT NULL,
    CONSTRAINT uq_outbox_dedupe_key UNIQUE (dedupe_key)
);
CREATE INDEX idx_outbox_status_next_attempt ON outbox_event (status, next_attempt_at);
